version: '3.8'

services:
  web:
    build: .
    ports:
      - "5009:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data.db
    volumes:
      - sqlite_data:/app
    restart: unless-stopped

volumes:
  sqlite_data:
    name: flask_sqlite_data